Feature/statistics
color-diary/color-diary pull request #13
Opened 2024-07-25 11:37 UTC by phantom2115

## Description

### 통계 페이지 기능 추가

![스크린샷 2024-07-25 오후 8 35 15](https://github.com/user-attachments/assets/5dc2d442-aca3-4e3a-afa5-5485b827571e)

## 작업내용

- [x] 명언 API get하여 새로고침 마다 새로운 명언 호출
- [x] 사용자가 작성한 색상, 태그 사용 빈도 순으로 정렬 후 차트에 표출

## ETC

### _[기타 사항]_

## 완료날짜

### 240725

2024-07-25 12:03 UTC, hyejinleeee commented on src/components/ui/chart.tsx
> +// Format: { THEME_NAME: CSS_SELECTOR }
이게 뭐죵??

2024-07-25 12:04 UTC, Park-Yuyeong requested changes
컴포넌트 분리하고 다시 올려주세요

2024-07-25 12:04 UTC, Park-Yuyeong commented on src/app/statistics/page.tsx
> +'use client';
page.tsx는 서버 컴포넌트로 작성해주세요!

2024-07-25 12:04 UTC, Park-Yuyeong commented on src/components/ui/chart.tsx
> +// Format: { THEME_NAME: CSS_SELECTOR }
이 주석은 무엇인가요?

2024-07-25 12:04 UTC, Park-Yuyeong commented on src/components/ui/chart.tsx
> +// Format: { THEME_NAME: CSS_SELECTOR }
아 shadcn 주석이구나. 지우죠

2024-07-25 12:05 UTC, hyejinleeee commented on src/app/statistics/page.tsx
> +const Page = () => {
StatisticsPage

2024-07-26 02:18 UTC, Park-Yuyeong commented on src/app/statistics/page.tsx
> +const Statistics = () => {
StatisticsPage로 이름 맞추기로 했잖아요..

2024-07-26 02:20 UTC, Park-Yuyeong approved these changes
수고하셨습니다

2024-07-26 02:21 UTC, hyejinleeee approved these changes

2024-07-26 02:21 UTC, merged